import defaultConfig from 'tailwindcss/defaultConfig';

export default {
  presets: [defaultConfig],
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-primary-container': '#006b78',
        'surface-variant': '#31353c',
        'on-tertiary': '#003731',
        'tertiary': '#e9fff9',
        'on-surface-variant': '#b9caca',
        'outline-variant': '#3a494a',
        'surface': '#10141a',
        'surface-container': '#1c2026',
        'tertiary-fixed': '#69f9e5',
        'on-tertiary-fixed': '#00201c',
        'surface-tint': '#00daf3',
        'tertiary-container': '#63f4e0',
        'surface-dim': '#10141a',
        'on-secondary-fixed': '#001f24',
        'on-primary-fixed-variant': '#004f58',
        'surface-bright': '#353940',
        'secondary': '#adccd2',
        'inverse-surface': '#dfe2eb',
        'on-error-container': '#ffdad6',
        'on-secondary-fixed-variant': '#2e4b51',
        'error-container': '#93000a',
        'tertiary-fixed-dim': '#46dcc9',
        'outline': '#849495',
        'secondary-fixed-dim': '#adccd2',
        'surface-container-highest': '#31353c',
        'on-primary': '#00363d',
        'secondary-fixed': '#c9e8ef',
        'surface-container-low': '#181c22',
        'on-tertiary-container': '#006e63',
        'primary-fixed': '#9cf0ff',
        'surface-container-lowest': '#0a0e14',
        'background': '#10141a',
        'secondary-container': '#2e4b51',
        'on-surface': '#dfe2eb',
        'primary-container': '#84edff',
        'error': '#ffb4ab',
        'primary': '#f0fcff',
        'inverse-primary': '#006875',
        'on-secondary-container': '#9cbac1',
        'on-tertiary-fixed-variant': '#005048',
        'on-error': '#690005',
        'primary-fixed-dim': '#00daf3',
        'on-primary-fixed': '#001f24',
        'inverse-on-surface': '#2d3137',
        'surface-container-high': '#262a31',
        'on-background': '#dfe2eb',
        'on-secondary': '#17353a',
      },
      fontFamily: {
        'headline': ['Space Grotesk', 'sans-serif'],
        'body': ['Manrope', 'sans-serif'],
        'label': ['Space Grotesk', 'sans-serif'],
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        'full': '0.75rem',
      },
    },
  },
};
